<?php
/**
 * SEO integrations for Fire Truck Center.
 *
 * @package Fire_Truck_Center
 */

/**
 * Return the page ID of the public truck catalog.
 *
 * @return int
 */
function ftc_get_truck_catalog_page_id() {
	static $catalog_page_id = null;

	if ( null !== $catalog_page_id ) {
		return $catalog_page_id;
	}

	$catalog_page_id = 0;
	$preferred_page  = get_page_by_path( 'search-fire-truck-for-sale' );

	if ( $preferred_page instanceof WP_Post && 'sale.php' === get_page_template_slug( $preferred_page ) ) {
		$catalog_page_id = (int) $preferred_page->ID;
		return $catalog_page_id;
	}

	$page_ids = get_posts(
		array(
			'post_type'      => 'page',
			'post_status'    => 'publish',
			'posts_per_page' => 1,
			'fields'         => 'ids',
			'meta_key'       => '_wp_page_template',
			'meta_value'     => 'sale.php',
		)
	);

	if ( ! empty( $page_ids ) ) {
		$catalog_page_id = (int) $page_ids[0];
	}

	return $catalog_page_id;
}

/**
 * Return the public catalog URL.
 *
 * The catalog is a regular page using sale.php, so resolving it by template
 * keeps breadcrumbs working if the page slug changes.
 *
 * @return string
 */
function ftc_get_truck_catalog_url() {
	$catalog_page_id = ftc_get_truck_catalog_page_id();

	return $catalog_page_id
		? get_permalink( $catalog_page_id )
		: home_url( '/search-fire-truck-for-sale/' );
}

/**
 * Get the equipment type selected by Search & Filter Pro.
 *
 * @return WP_Term|false
 */
function ftc_get_filtered_equipment_type() {
	if ( empty( $_GET['_sft_equipment_type'] ) || ! is_string( $_GET['_sft_equipment_type'] ) ) {
		return false;
	}

	$slug = sanitize_title( wp_unslash( $_GET['_sft_equipment_type'] ) );

	if ( empty( $slug ) ) {
		return false;
	}

	$term = get_term_by( 'slug', $slug, 'equipment_type' );

	return $term instanceof WP_Term ? $term : false;
}

/**
 * Build catalog-aware Rank Math breadcrumbs.
 *
 * @param array $crumbs Breadcrumb items generated by Rank Math.
 * @return array
 */
function ftc_rank_math_breadcrumb_items( $crumbs ) {
	if ( ! is_singular( 'truck' ) && ! is_page_template( 'sale.php' ) && ! is_tax( 'equipment_type' ) ) {
		return $crumbs;
	}

	$home = array( __( 'Home', 'fire-truck-center' ), home_url( '/' ) );
	if ( is_array( $crumbs ) && ! empty( $crumbs[0] ) ) {
		$home = $crumbs[0];
	}

	$catalog_url   = ftc_get_truck_catalog_url();
	$catalog_crumb = array( __( 'Available Trucks', 'fire-truck-center' ), $catalog_url );

	if ( is_tax( 'equipment_type' ) ) {
		$equipment_type = get_queried_object();
		$current_url    = $catalog_url;
		if ( $equipment_type instanceof WP_Term ) {
			$term_url = get_term_link( $equipment_type );
			if ( ! is_wp_error( $term_url ) ) {
				$current_url = $term_url;
			}
		}

		return array(
			$home,
			$catalog_crumb,
			array(
				$equipment_type instanceof WP_Term ? $equipment_type->name : single_term_title( '', false ),
				$current_url,
			),
		);
	}

	if ( is_page_template( 'sale.php' ) ) {
		$equipment_type = ftc_get_filtered_equipment_type();

		if ( $equipment_type ) {
			return array(
				$home,
				$catalog_crumb,
				array( $equipment_type->name, $catalog_url ),
			);
		}

		return array(
			$home,
			array( __( 'Available Trucks', 'fire-truck-center' ), $catalog_url ),
		);
	}

	$trail = array( $home, $catalog_crumb );
	$terms = get_the_terms( get_queried_object_id(), 'equipment_type' );

	if ( ! is_wp_error( $terms ) && ! empty( $terms ) ) {
		$equipment_type = reset( $terms );
		$term_url       = get_term_link( $equipment_type );
		$trail[]        = array(
			$equipment_type->name,
			is_wp_error( $term_url ) ? $catalog_url : $term_url,
		);
	}

	$trail[] = array( get_the_title( get_queried_object_id() ), get_permalink( get_queried_object_id() ) );

	return $trail;
}
add_filter( 'rank_math/frontend/breadcrumb/items', 'ftc_rank_math_breadcrumb_items', 20 );

/**
 * Make public Truck Type archives indexable.
 *
 * Rank Math removes the canonical tag whenever an archive resolves to
 * noindex. These term pages are public inventory landing pages with unique
 * headings and ACF content, so they should be indexable and retain their
 * canonical URL.
 *
 * @param array $robots Robots directives generated by Rank Math.
 * @return array
 */
function ftc_equipment_type_robots( $robots ) {
	if ( ! is_tax( 'equipment_type' ) ) {
		return $robots;
	}

	$robots = is_array( $robots ) ? $robots : array();
	$robots = array_filter(
		$robots,
		static function ( $directive ) {
			return ! in_array( $directive, array( 'noindex', 'nofollow' ), true );
		}
	);

	$robots['index']  = 'index';
	$robots['follow'] = 'follow';

	return $robots;
}
add_filter( 'rank_math/frontend/robots', 'ftc_equipment_type_robots', 99 );

/**
 * Keep faceted variations of a Truck Type archive canonical to the term URL.
 *
 * @param string $canonical Canonical URL generated by the SEO plugin.
 * @return string
 */
function ftc_equipment_type_canonical_url( $canonical ) {
	if ( ! is_tax( 'equipment_type' ) ) {
		return $canonical;
	}

	$term_url = get_term_link( get_queried_object() );

	return is_wp_error( $term_url ) ? $canonical : $term_url;
}
add_filter( 'rank_math/frontend/canonical', 'ftc_equipment_type_canonical_url', 20 );
add_filter( 'wpseo_canonical', 'ftc_equipment_type_canonical_url', 20 );

/**
 * Output an ItemList for the inventory shown on a Truck Type archive.
 *
 * Rank Math supplies WebPage/CollectionPage and BreadcrumbList nodes; this
 * node describes the actual trucks in the archive's main result query.
 *
 * @return void
 */
function ftc_output_equipment_type_item_list_schema() {
	if ( ! is_tax( 'equipment_type' ) || is_feed() ) {
		return;
	}

	global $wp_query;

	$term     = get_queried_object();
	$term_url = $term instanceof WP_Term ? get_term_link( $term ) : false;
	if ( ! $term instanceof WP_Term || is_wp_error( $term_url ) || ! $wp_query instanceof WP_Query ) {
		return;
	}

	$items    = array();
	$position = 1;

	foreach ( (array) $wp_query->posts as $truck ) {
		if ( ! $truck instanceof WP_Post || 'truck' !== $truck->post_type ) {
			continue;
		}

		$items[] = array(
			'@type'    => 'ListItem',
			'position' => $position,
			'name'     => get_the_title( $truck ),
			'url'      => get_permalink( $truck ),
		);
		++$position;
	}

	$schema = array(
		'@context'          => 'https://schema.org',
		'@type'             => 'ItemList',
		'@id'               => trailingslashit( $term_url ) . '#inventory',
		'name'              => sprintf(
			/* translators: %s: truck type term name. */
			__( '%s inventory', 'fire-truck-center' ),
			$term->name
		),
		'url'               => $term_url,
		'numberOfItems'     => count( $items ),
		'itemListOrder'     => 'https://schema.org/ItemListOrderDescending',
		'itemListElement'   => $items,
		'mainEntityOfPage'  => array(
			'@type' => 'CollectionPage',
			'@id'   => trailingslashit( $term_url ) . '#webpage',
		),
	);
	?>
	<script type="application/ld+json"><?php echo wp_json_encode( $schema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></script>
	<?php
}
add_action( 'wp_head', 'ftc_output_equipment_type_item_list_schema', 35 );

/**
 * Merge the official social profiles into an Organization Schema entity.
 *
 * @param array $entity Organization Schema entity.
 * @return array
 */
function ftc_add_organization_same_as( $entity ) {
	$profiles = array(
		'https://www.instagram.com/firetruckcenter/',
		'https://www.youtube.com/@FireTruckCenter',
	);
	$same_as  = isset( $entity['sameAs'] ) ? (array) $entity['sameAs'] : array();

	$entity['sameAs'] = array_values( array_unique( array_merge( $same_as, $profiles ) ) );

	return $entity;
}

/**
 * Add social profiles to Rank Math's Organization node.
 *
 * @param array $data Rank Math JSON-LD graph.
 * @return array
 */
function ftc_rank_math_organization_same_as( $data ) {
	if ( ! is_array( $data ) ) {
		return $data;
	}

	foreach ( $data as $key => $entity ) {
		if ( ! is_array( $entity ) || empty( $entity['@type'] ) ) {
			continue;
		}

		$types = (array) $entity['@type'];
		if ( ! array_intersect( array( 'Organization', 'AutoDealer', 'LocalBusiness' ), $types ) ) {
			continue;
		}

		$data[ $key ] = ftc_add_organization_same_as( $entity );
	}

	return $data;
}
add_filter( 'rank_math/json_ld', 'ftc_rank_math_organization_same_as', 99 );

/**
 * Keep the same Organization profiles when Yoast SEO is active instead.
 *
 * @param array $data Yoast Organization Schema entity.
 * @return array
 */
function ftc_yoast_organization_same_as( $data ) {
	return is_array( $data ) ? ftc_add_organization_same_as( $data ) : $data;
}
add_filter( 'wpseo_schema_organization', 'ftc_yoast_organization_same_as', 99 );

/**
 * Normalize an ACF value for a text Schema property.
 *
 * @param mixed $value Raw field value.
 * @return string
 */
function ftc_schema_text_value( $value ) {
	if ( $value instanceof WP_Term ) {
		$value = $value->name;
	} elseif ( is_array( $value ) ) {
		if ( isset( $value['name'] ) ) {
			$value = $value['name'];
		} elseif ( ! empty( $value ) ) {
			$value = reset( $value );
			if ( $value instanceof WP_Term ) {
				$value = $value->name;
			}
		}
	}

	return is_scalar( $value )
		? trim( html_entity_decode( wp_strip_all_tags( (string) $value ), ENT_QUOTES | ENT_HTML5, get_bloginfo( 'charset' ) ) )
		: '';
}

/**
 * Return the first populated ACF text field from a list of possible names.
 *
 * @param int   $post_id     Truck post ID.
 * @param array $field_names ACF field names.
 * @return string
 */
function ftc_get_first_schema_field( $post_id, $field_names ) {
	if ( ! function_exists( 'get_field' ) ) {
		return '';
	}

	foreach ( $field_names as $field_name ) {
		$value = ftc_schema_text_value( get_field( $field_name, $post_id ) );
		if ( '' !== $value ) {
			return $value;
		}
	}

	return '';
}

/**
 * Return the first term name assigned to a truck.
 *
 * @param int    $post_id Truck post ID.
 * @param string $taxonomy Taxonomy name.
 * @return string
 */
function ftc_get_schema_term_name( $post_id, $taxonomy ) {
	$terms = get_the_terms( $post_id, $taxonomy );

	if ( is_wp_error( $terms ) || empty( $terms ) ) {
		return '';
	}

	return ftc_schema_text_value( reset( $terms ) );
}

/**
 * Collect the featured image and ACF gallery images for Vehicle Schema.
 *
 * @param int $post_id Truck post ID.
 * @return array
 */
function ftc_get_vehicle_schema_images( $post_id ) {
	$images         = array();
	$featured_image = get_the_post_thumbnail_url( $post_id, 'full' );

	if ( $featured_image ) {
		$images[] = esc_url_raw( $featured_image );
	}

	$rows = function_exists( 'get_field' ) ? get_field( 'image_slider', $post_id ) : array();
	if ( is_array( $rows ) ) {
		foreach ( $rows as $row ) {
			if ( empty( $row['slide_image'] ) ) {
				continue;
			}

			$image     = $row['slide_image'];
			$image_url = '';

			if ( is_array( $image ) && ! empty( $image['url'] ) ) {
				$image_url = $image['url'];
			} elseif ( is_numeric( $image ) ) {
				$image_url = wp_get_attachment_image_url( (int) $image, 'full' );
			} elseif ( is_string( $image ) ) {
				$image_url = $image;
			}

			if ( $image_url ) {
				$images[] = esc_url_raw( $image_url );
			}
		}
	}

	return array_values( array_unique( array_filter( $images ) ) );
}

/**
 * Map the truck Status field to a Schema.org availability value.
 *
 * @param int $post_id Truck post ID.
 * @return string
 */
function ftc_get_vehicle_schema_availability( $post_id ) {
	$status = ftc_get_first_schema_field( $post_id, array( 'status_sibgle', 'status' ) );
	$status = sanitize_key( str_replace( array( ' ', '_' ), '-', strtolower( $status ) ) );

	if ( in_array( $status, array( 'sold', 'sold-out', 'out-of-stock' ), true ) ) {
		return 'https://schema.org/SoldOut';
	}

	if ( in_array( $status, array( 'pending', 'sale-pending' ), true ) ) {
		return 'https://schema.org/LimitedAvailability';
	}

	return 'https://schema.org/InStock';
}

/**
 * Get the model from a dedicated field or derive it from the truck title.
 *
 * Older inventory records do not have a separate model field. For those
 * records, the title is normalized by removing the leading year, make and
 * trailing stock status.
 *
 * @param int    $post_id Truck post ID.
 * @param string $name    Truck title.
 * @param string $make    Truck make.
 * @param string $year    Model year.
 * @return string
 */
function ftc_get_vehicle_schema_model( $post_id, $name, $make, $year ) {
	$model = ftc_get_first_schema_field( $post_id, array( 'model', 'truck_model', 'model_name' ) );
	if ( '' !== $model ) {
		return $model;
	}

	$model = $name;
	if ( '' !== $year ) {
		$model = preg_replace( '/^' . preg_quote( $year, '/' ) . '\\s+/i', '', $model );
	}
	if ( '' !== $make ) {
		$model = preg_replace( '/^' . preg_quote( $make, '/' ) . '\\s+/i', '', $model );
	}

	$model = preg_replace( '/\s*[-–—]?\s*(?:sold|sale pending)\s*$/i', '', $model );

	return trim( (string) $model, " \t\n\r\0\x0B-–—" );
}

/**
 * Convert a formatted numeric ACF value into a Schema-safe number.
 *
 * @param mixed $value Raw numeric value.
 * @return int|float|null
 */
function ftc_schema_number_value( $value ) {
	if ( is_string( $value ) ) {
		$value = str_replace( array( '$', ',', ' ' ), '', $value );
	}

	if ( ! is_numeric( $value ) ) {
		return null;
	}

	$number = (float) $value;

	return floor( $number ) === $number ? (int) $number : $number;
}

/**
 * Build the Vehicle and Offer JSON-LD entity from truck fields.
 *
 * @param int $post_id Truck post ID.
 * @return array
 */
function ftc_get_vehicle_schema( $post_id ) {
	$url          = get_permalink( $post_id );
	$name         = ftc_schema_text_value( get_the_title( $post_id ) );
	$make         = ftc_get_first_schema_field( $post_id, array( 'make', 'manufacturer' ) );
	$year         = ftc_get_first_schema_field( $post_id, array( '_year', 'year' ) );
	$sku          = ftc_get_first_schema_field( $post_id, array( 'sku' ) );
	$mileage      = function_exists( 'get_field' ) ? ftc_schema_number_value( get_field( 'mileage', $post_id ) ) : null;
	$price        = function_exists( 'get_field' ) ? ftc_schema_number_value( get_field( '_price', $post_id ) ) : null;
	$truck_type   = ftc_get_schema_term_name( $post_id, 'equipment_type' );
	$images       = ftc_get_vehicle_schema_images( $post_id );
	$availability = ftc_get_vehicle_schema_availability( $post_id );

	if ( '' === $make ) {
		$make = ftc_get_schema_term_name( $post_id, 'truck_brands' );
	}
	$model = ftc_get_vehicle_schema_model( $post_id, $name, $make, $year );

	$offer = array(
		'@type'         => 'Offer',
		'@id'           => trailingslashit( $url ) . '#offer',
		'url'           => $url,
		'availability'  => $availability,
		'itemCondition' => 'https://schema.org/UsedCondition',
	);

	if ( null !== $price && $price > 0 ) {
		$offer['price']         = $price;
		$offer['priceCurrency'] = 'USD';
	}

	$schema = array(
		'@context'      => 'https://schema.org',
		'@type'         => 'Vehicle',
		'@id'           => trailingslashit( $url ) . '#vehicle',
		'name'          => $name,
		'url'           => $url,
		'bodyType'      => 'Fire Truck',
		'itemCondition' => 'https://schema.org/UsedCondition',
		'offers'        => $offer,
	);

	if ( '' !== $make ) {
		$schema['brand']        = array( '@type' => 'Brand', 'name' => $make );
		$schema['manufacturer'] = array( '@type' => 'Organization', 'name' => $make );
	}
	if ( '' !== $model ) {
		$schema['model'] = $model;
	}
	if ( '' !== $year ) {
		$schema['vehicleModelDate'] = $year;
		$schema['modelDate']        = $year;
	}
	if ( null !== $mileage && $mileage >= 0 ) {
		$schema['mileageFromOdometer'] = array(
			'@type'    => 'QuantitativeValue',
			'value'    => $mileage,
			'unitCode' => 'SMI',
			'unitText' => 'miles',
		);
	}
	if ( '' !== $sku ) {
		$schema['sku'] = $sku;
		$schema['mpn'] = $sku;
	}
	if ( '' !== $truck_type ) {
		$schema['vehicleConfiguration'] = $truck_type;
	}
	if ( ! empty( $images ) ) {
		$schema['image'] = $images;
	}

	return $schema;
}

/**
 * Output one automatically generated Vehicle JSON-LD entity per truck.
 *
 * Existing manual Vehicle/Car nodes from SEO plugins are removed by the
 * filters below, and header.php no longer prints the legacy microdata field.
 *
 * @return void
 */
function ftc_output_vehicle_schema() {
	if ( ! is_singular( 'truck' ) ) {
		return;
	}

	$schema = ftc_get_vehicle_schema( get_queried_object_id() );
	?>
	<script type="application/ld+json"><?php echo wp_json_encode( $schema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></script>
	<?php
}
add_action( 'wp_head', 'ftc_output_vehicle_schema', 30 );

/**
 * Check whether a Schema node represents a Vehicle or Car.
 *
 * @param mixed $entity Schema graph node.
 * @return bool
 */
function ftc_is_vehicle_schema_entity( $entity ) {
	if ( ! is_array( $entity ) || empty( $entity['@type'] ) ) {
		return false;
	}

	return ! empty( array_intersect( array( 'Vehicle', 'Car' ), (array) $entity['@type'] ) );
}

/**
 * Remove any manually configured Rank Math Vehicle/Car node before output.
 *
 * @param array $data Rank Math JSON-LD graph.
 * @return array
 */
function ftc_remove_rank_math_vehicle_schema( $data ) {
	if ( ! is_singular( 'truck' ) || ! is_array( $data ) ) {
		return $data;
	}

	foreach ( $data as $key => $entity ) {
		if ( ftc_is_vehicle_schema_entity( $entity ) ) {
			unset( $data[ $key ] );
		}
	}

	return $data;
}
add_filter( 'rank_math/json_ld', 'ftc_remove_rank_math_vehicle_schema', 90 );

/**
 * Remove any manually configured Yoast Vehicle/Car node before output.
 *
 * @param array $graph Yoast JSON-LD graph.
 * @return array
 */
function ftc_remove_yoast_vehicle_schema( $graph ) {
	if ( ! is_singular( 'truck' ) || ! is_array( $graph ) ) {
		return $graph;
	}

	return array_values( array_filter( $graph, function ( $entity ) {
		return ! ftc_is_vehicle_schema_entity( $entity );
	} ) );
}
add_filter( 'wpseo_schema_graph', 'ftc_remove_yoast_vehicle_schema', 90 );

/**
 * Hide the obsolete manual microdata field on truck edit screens.
 *
 * Existing saved values remain in the database but are no longer rendered.
 *
 * @param array $field ACF field configuration.
 * @return array|false
 */
function ftc_hide_manual_truck_microdata_field( $field ) {
	if ( ! is_admin() ) {
		return $field;
	}

	$post_id   = isset( $_GET['post'] ) ? absint( $_GET['post'] ) : 0;
	$post_type = $post_id ? get_post_type( $post_id ) : '';

	if ( 'truck' === $post_type || ( isset( $_GET['post_type'] ) && 'truck' === sanitize_key( wp_unslash( $_GET['post_type'] ) ) ) ) {
		return false;
	}

	return $field;
}
add_filter( 'acf/prepare_field/name=microdata', 'ftc_hide_manual_truck_microdata_field' );
